script: "bundle exec rspec spec"

language: ruby

rvm:
  - 2.5
  - 2.6
  - 2.7
  - jruby

services:
  - mongodb

gemfile:
  - gemfiles/mongoid5.gemfile
  - gemfiles/mongoid6.gemfile
  - gemfiles/mongoid7.gemfile

jobs:
  exclude:
    - rvm: 2.7
      gemfile: gemfiles/mongoid6.gemfile
    - rvm: 2.7
      gemfile: gemfiles/mongoid5.gemfile
